### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by swebb** [tsa/vu8#7] opened 2012-01-30 01:07 UTC
How do you install vu8?

**Comment by insidewhy** [comment] 2012-01-30 08:43
make
make install

You can control-C after the first make and do "make config" or just use cmake to change options.

**Comment by swebb** [comment] 2012-01-31 00:30
That didn't work for me:

[ 20%] Building CXX object CMakeFiles/vu8.dir/Context.o
make[3]: **\* No rule to make target `/usr/local/lib/libv8.so', needed by`libvu8.so'.  Stop.

I managed to get vu8 compiled by hacking around with the cmake script. But it wasn't ideal.

**Comment by insidewhy** [comment] 2012-01-31 10:43
Strange, that shouldn't happen as vu8 determines the path to libv8 itself during build; and if it doesn't find it the variable isn't set. So I'm not sure how it could get set to a file location that doesn't exist (maybe you installed v8 then moved it or updated the location manually using ccmake?)

Did you use the latest version? Can you do "make clean" after updating? I can't reproduce this kind of problem at all nor see how it happened with the current latest code.

**Comment by tsa** [comment] 2012-03-21 15:23
Been waiting on your response for over 2 months now so closing. Thanks for reporting your problem and please re-open if you have anything further to add.

**Closed as completed by tsa** 2012-03-21 15:23 UTC
